/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author victor
 */
public class ScoreBoard extends javax.swing.JPanel {

    private int scoreP1;

    private int scoreP2;

    /**
     * Creates new form ScoreBoard
     */
    public ScoreBoard() {
        initComponents();
        incrementScoreP1(0);
        incrementScoreP2(0);

    }

    public void incrementScoreP1(int increment) {
        scoreP1 += increment;
        /* scoreLabel.setText("Score for " + 
                Config.getInstance().getPlayerName() + 
                ": " + score);
         */
        scoreLabel.setText("Score for "
                + Config.getInstance().getPlayerName1()
                + ": " + scoreP1 + "; Score for "
                + Config.getInstance().getPlayerName2()
                + ": " + scoreP2);

    }
    
    
    public void printScore(){
     scoreLabel.setText("Score for "
                + Config.getInstance().getPlayerName1()
                + ": " + getScoreP1() + "; Score for "
                + Config.getInstance().getPlayerName2()
                + ": " + getScoreP2());
    
    }
    
    public void incrementScoreP2(int increment) {
        scoreP2 += increment;
        /* scoreLabel.setText("Score for " + 
                Config.getInstance().getPlayerName() + 
                ": " + score);
         */
        scoreLabel.setText("Score for "
                + Config.getInstance().getPlayerName1()
                + ": " + scoreP1 + "; Score for "
                + Config.getInstance().getPlayerName2()
                + ": " + scoreP2);

    }

    public void pause() {
        scoreLabel.setText("Paused");
    }

    public void setScoreP1(int score) {
        this.scoreP1 = scoreP1;
        incrementScoreP1(0);
    }

    public void setScoreP2(int score) {
        this.scoreP2 = scoreP2;
        incrementScoreP1(0);
    }
    
     public int getScoreP1() {
        return scoreP1;
    }

    public int getScoreP2() {
        return scoreP2;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scoreLabel = new javax.swing.JLabel();

        scoreLabel.setText("Score: 0");
        add(scoreLabel);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel scoreLabel;
    // End of variables declaration//GEN-END:variables
}
